// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egznzgrncxlqvecpuubs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnem56Z3JuY3hscXZlY3B1dWJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MzI0MzQsImV4cCI6MjA3MzIwODQzNH0.mvL61mlaiSBPIOBb4xhMt1nQT4vf2r9rw7hFxqvgiGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});